aio-libs/aiomysql

aiomysql/sa/connection.py, aiomysql/sa/result.py, tests/sa/test_sa_connection.py
In ``ResultProxy`` class ``cursor.close()`` called without `` yield from`` since ``cursor.close`` is coroutine ``ResultProxy.close`` must be coroutine too. This PR fixes this issue and all warnings in travisci like:
```
<CoroWrapper Cursor.close() running at /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/aiomysql/cursors.py:148, 
created at /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/aiomysql/sa/result.py:322> was never yielded from
```
see this [travis bulild]( https://travis-ci.org/aio-libs/aiomysql/jobs/60567222).
But I do not know proper way how to fix following line:
```python
self._weak = weakref.ref(self, lambda wr: cursor.close())
```
may be with ``asyncio.Task``:
```python
self._weak = weakref.ref(self, lambda wr: asyncio.Task(cursor.close(), …
```
=> Fix result proxy close method

aiomysql/pool.py, tests/test_pool.py
Should fix #25 and #16 
@asvetlov please review.
=> fix connection timeouts in pool

aiomysql/connection.py, tests/test_connection.py
Fix ported from https://github.com/PyMySQL/PyMySQL/pull/403
=> Raise exception if previous cursor was not closed

aiomysql/sa/connection.py, aiomysql/sa/result.py, aiomysql/sa/transaction.py, aiomysql/utils.py, tests/pep492/test_async_with.py
Should resolve https://github.com/aio-libs/aiomysql/issues/51
=> Even more async support

aiomysql/connection.py
Hi,
When I use aiomysql 0.0.8 on Window10 x64 using Python3.5.2 to connect mysql server( version 5.1.73) on Centos6.4 x64, I got:
_File "G:\git\aiowebapp\.env\lib\site-packages\aiomysql\connection.py", line 657, in _request_authentication
if self._auth_plugin_name in ('', 'mysql_native_password'):
AttributeError: 'Connection' object has no attribute '_auth_plugin_name'_
I checked the Server Greeting wirshark cap, found the "PLUGIN_AUTH" bit in "server capabilities" is 0, which means "self.server_capabilities & CLIENT.PLUGIN_AUTH" is False in function "_get_server_information(self)",  so attribute '_auth_plugin_name_' is undefined here.
And then the "AttributeError" occur in  `_request_authentication(self):
if self.server_capabilities & CLIENT.PLUGIN_AUTH:`
And when I do this fix, the …
=> To avoid AttributeError in function _request_authentication(self)

aiomysql/connection.py, aiomysql/pool.py, aiomysql/sa/engine.py, tests/test_pool.py
Based on similar feature from aiopg https://github.com/aio-libs/aiopg/pull/373
=> Pool recylce

docs/tutorial.rst
The example introduction said `autocommit=False`, but the code below is obviously demonstrating `autocommit=True`. Updating documentation to match example.
=> Correct autocommit example introduction to match

aiomysql/sa/connection.py, tests/sa/test_sa_connection.py
For the SQLAlchemy engine, the `_distill_params` function in `sa/connection.py` returns an empty list [] when no arguments are passed.
This results in [] passed to cursor.execute as the `args` argument causing if check 
https://github.com/aio-libs/aiomysql/blob/master/aiomysql/cursors.py#L237
to string format an empty list, erroring with:
```py
File "/usr/local/lib/python3.6/site-packages/aiomysql/utils.py", line 75, in __await__
resp = yield from self._coro
File "/usr/local/lib/python3.6/site-packages/aiomysql/sa/connection.py", line 77, in _execute
yield from cursor.execute(query, dp)
File "/usr/local/lib/python3.6/site-packages/aiomysql/cursors.py", line 238, in execute
query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
```
=> proper argument for cursor.execute (for sa engine)

docs/sa.rst, examples/example_simple_sa.py, examples/example_simple_sa_oldstyle.py
I think I did the old-style correctly.
At first I was doing `conn.execute('commit')`, but then I realized the connection object has a commit method that does a bit more so I switched to using that.
Let me know if I missed anything.
=> commit in the examples

aiomysql/connection.py, tests/test_ssl.py
Git closed last one when i force pushed.
Long discussion in #225
@jettify @terrisgit - new PR, less code :D
Also credit to Alex as I made a test where MySQL then tried to renegotiate the auth plugin, so I imported his `process_auth` function (and github realises it was him :smile:)
@jettify whats next.
=> SSL Support (plus mysql_clear_password plugin for RDS)

requirements-dev.txt, setup.py
This should repair #302 until a better fix lands to support PyMySQL 0.9.0
=> Apply more conservative version pinning

aiomysql/connection.py, docs/connection.rst, requirements-dev.txt, setup.py, tests/test_basic.py, tests/test_connection.py
Fixes #303 #302 
So this was a weird one. I'm assuming PyMySQL changed some flag somewhere but it was refusing to connect unless we provided some client connection arguments.  I just mimic'd how PyMySQL does it, so when connecting it will send across pid, program name, library name etc...
Also fixed the obvious moving of password functions. Am going to add support for authentication_plugins `caching_sha2_password` and `sha256_password` after this PR is merged as those require PyMySQL methods to be rewritten async-style.
PyMySQL has also changed the default charset so that pwn'd a few tests so have updated the checks which should do for now.
Only this thats annoying me is getting the version in connection.py as one cant import __init__.py, simple answer would be to use bumpversion and …
=> PyMySQL 0.9 Update

aiomysql/connection.py, docs/connection.rst, examples/example_ssl.py, tests/conftest.py, tests/test_sha_connection.py, tests/test_ssl.py
Fixes #302 
Fixes #297 
This PR contains the bulk of what PyMySQL 0.9.0 added which was support for MySQL 8+'s use of the `sha256_password` and `caching_sha2_password` authentication plugin.
I've also parameterised `mysql_tag` so it now tests connecting to MySQL 5.6 and 8.0 using SSL and as MySQL 8 defaults to the `caching_sha2_password`, that is tested by the current SSL unit tests.
I'm planning on creating a fixture that allows me to skip tests depending on the value of `mysql_tag` so I can target a few specific tests to 8.0 which should further test the `sha256_password` plugin.
---
@jettify I'm assuming you have no issue with me making a PR to move the other tests to using the MySQL server provided by the container, that way I think we can get rid of all the travis matrix except …
=> MySQL 8 Compatibility and SHA256 authentication plugin support

aiomysql/connection.py, tests/test_issues.py
Fixes #323 
Inserting a binary object it raises a warning, this fixes it. Inspiration taken from https://github.com/PyMySQL/mysqlclient-python/pull/106
@jettify review please. I don't *think* it will cause any adverse effects.
=> Fixes warning when inserting binary strings

.travis.yml, CONTRIBUTING.rst, requirements-dev.txt
On python 3.5+ following the CONTRIBUTING steps fails when `tests/conftest.py` tries to `import uvloop`. This patch adds uvloop with a conditional on python >= 3.5, and removes the now unnecessary install step from the travis install steps.
Reproduces on stock Ubuntu 18.04.1 LTS with Python 3.6.5.
=> Add version-conditional uvloop install to requirements-dev.txt

aiomysql/pool.py, tests/test_pool.py
In our production environment, we occasionally experience connection timeouts that "stick" in the aiomysql Pool. Every subsequent connection acquired from the pool will fail on first use.
My production environment full traceback (with private code redacted): https://gist.github.com/TimothyFitz/2d929f907c4cad47a7c8da8e0944b19e
This PR adds a test to simulate our production failure by directly calling `connection_lost` on a connection in the free pool.
The pool code already checks for gracefully closed connection via `_reader.at_eof()`. The fix is to also check for `_reader.exception()`.
I think #132 accidentally conflated two issues, and the fix identified there is needed in addition to pool recycling: https://github.com/aio-libs/aiomysql/issues/132#issuecomment-336651086
Tested on: …
=> Don't reuse connections when StreamReader has an exception

aiomysql/cursors.py
=> fix the python 3.7 compatibility

README.rst
The basic example is almost the same with the following connection pool example.
And it uses `pool.get()`, which was deprecated in 2016, 8c1117948c144420bb37f712b284810f45750f5e
=> remove basic example in README.rst

aiomysql/sa/connection.py, tests/sa/test_sa_connection.py
error: aiomysql doesn't support executemany
``` python
import asyncio
import sqlalchemy as sa
from sqlalchemy.sql.ddl import CreateTable, DropTable
from aiomysql.sa import create_engine
from sqlalchemy.sql.expression import bindparam
metadata = sa.MetaData()
User = sa.Table(
'user',
metadata,
sa.Column(
'id',
sa.Integer,
autoincrement=True,
primary_key=True,
nullable=False,
),
sa.Column(
'name',
sa.String(16),
nullable=False,
)
)
async def test_executemany(loop):
engine = await create_engine(
user="aiomysql",
db="test_pymysql",
host="127.0.0.1",
password="mypass",
port=3306,
loop=loop,
echo=True,
)
async with engine.acquire() as conn:
await conn.execute(CreateTable(User))
await conn.execute(User.insert().values([{"name": "test1"}, {"name": "test2"}]))
async with …
```
=> fix: support executemany

aiomysql/connection.py, aiomysql/cursors.py, tests/test_connection.py
Makes it so when you specify `connect_timeout` its actually respected instead of ignored :wink: 
Fixes #257
@jettify mind reviewing this if you get a chance.
=> connect_timeout fix

docs/connection.rst
It was not clear to me whether these are milliseconds or seconds.
=> Specify unit of connect_timeout in docs

aiomysql/connection.py
I see the comment "# TODO somehow import version from \__init__.py" in the connection.py.
Since A import B and B import A will cause **cycle import**, \__init__.py has imported sth from conncetion, so I import version in the function inner to avoid the problem.
=> import version from __init.py__

README.rst, aiomysql/sa/result.py, docs/index.rst
This allows the `async for` syntax to be used with `ResultProxy` and `Cursor` objects in python 3.7.
Fixes #394 
Fixes #386 
Fixes #317
=> Fix legacy __aiter__ methods

docs/index.rst
This updates the old-styled @asyncio.coroutine -> async def coroutine and updates yield from -> await.
Closes https://github.com/aio-libs/aiomysql/issues/436
This PR updates the old-styled @asyncio.coroutine -> async def coroutine and updates yield from -> await keyword.
Yes 
None
* Make sure to use full sentences with correct case and punctuation, for example: `Fix …
=> docs/index.rst: Updated tutorial to native coroutines

aiomysql/sa/engine.py, tests/sa/test_sa_default.py
Fix https://github.com/aio-libs/aiomysql/issues/455
No changes
https://github.com/aio-libs/aiomysql/issues/455
=> added support for sqlalchemy default parameters #455

aiomysql/sa/connection.py, examples/example_oldstyle.py, examples/example_pool_oldstyle.py, tests/conftest.py
=> Fixed flake8 errors

.travis.yml, tests/conftest.py, tests/test_async_with.py, tests/test_connection.py
* Fix tests to pass on python 3.7 and 3.8 versions
* Support python 3.7 and 3.8 in Travis CI
=> Support python 3.7 and 3.8 in travis CI

.github/workflows/ci.yml, .github/workflows/lint.yml, .travis.yml, README.rst, docs/index.rst, requirements-dev.txt, setup.py, tests/conftest.py, tests/test_issues.py, tests/test_load_local.py, tests/test_pool.py, tests/test_sha_connection.py
- migrate travis CI tests to github actions, fixes #541
- release publishing is not currently implemented
- drop python 3.5 and 3.6 support
- run tests for python 3.7 to 3.9
- python 3.10 tests fail due to removed `loop` argument, therefore currently disabled
- this is only an issue in the test suite afaik
- python 3.11 tests currently fail to install `uvloop`, therefore currently disabled
- see https://github.com/MagicStack/uvloop/issues/450
- run tests for MySQL 5.7 and 8.0 `latest`
- run tests for MariaDB 10.2 to 10.7 and `latest`
- bump dev/test dependencies
- migrate deprecated test syntax
- remove docker integration from tests, for automated builds this is now covered by github actions
- async test methods have been broken before already …
=> Implement CI in github actions

CHANGES.txt, aiomysql/connection.py, docs/connection.rst
This ports PyMySQL's change: https://github.com/PyMySQL/PyMySQL/pull/755
We no longer implicitly send `sys.argv[0]` to the DB server by default.
For the majority of users this should not be relevant, if you need this value you can still pass it explicitly.
fixes #620, closes #621
=> Don't send sys.argv[0] as program_name to MySQL server by default

docs/connection.rst
Fix docs formatting.
We should adjust the local docs generation to use the RTD theme, that will make it easier to spot this in the future.
no.
#681
=> fix formatting in documentation after #681

.github/workflows/ci.yml, .github/workflows/lint.yml, CHANGES.txt
Fail Lint workflow when pyroma rating is not 10/10.
Unless this is implemented the pyroma action doesn't do much, as it's easily missed when not explicitly looking at the step output.
no
=> move pyroma to lint ci workflow, fail if rating is below 10/10

CHANGES.txt, aiomysql/connection.py, aiomysql/pool.py
Currently tests on timed out connections fail on MySQL 8.0.
This ports https://github.com/PyMySQL/PyMySQL/pull/540.
Interestingly, the PyMySQL issue originally referred to MariaDB, however, I don't see this behavior on currently supported MariaDB versions.
MySQL 8.0 does behave this way though.
In addition to porting the connection related changes, due to us having a pool, we will also need to adjust the pool logic.
Currently the connection pool attempts to not return closed connections in `Pool.acquire` via `Pool._fill_free_pool`.
At this time the connection is not yet considered closed, that will only be determined on the next `Connection._read_packet`.
When MySQL 8.0 closes the connection on us e.g. due to a timeout, the connection will still have the packet containing the error …
=> Fix MySQL 8.0 tests, properly close timed out connections

tests/_testutils.py, tests/base.py, tests/conftest.py
Remove legacy async syntax from tests, as this is not needed anymore for any currently supported python version.
`tests._testutils.run_until_complete` is not referenced anymore since moving to `pytest.mark.run_loop` in 819d4ec5fb967a679cad134eba885a1ce4bb5cee, therefore removed.
No.
No
=> remove deprecated asyncio.coroutines syntax from tests

.github/workflows/ci.yml
First set of changes split from #686 in order to split changes into smaller chunks with smaller diffs.
No functional difference, just simplified workflow to build future changes on.
=> restructure CI workflow

tests/test_cursor.py, tests/test_sscursor.py
When changing the order of some tests, e.g. not running asyncio and uvloop tests next to each other, these missing prepares can currently lead to test failures.
This failed e.g. in #693.
I have not yet checked why this wouldn't always fail, as it seems that sometimes these tables are available, but this fixes the tests to only rely on data expected to be present.
=> ensure test_scroll_errors and test_sscursor_scroll_errors initialize their tables

.github/workflows/ci.yml, tests/conftest.py
Second set of changes split from #686.
This allows passing a mysql address via pytest argument, preparing for being able to test more databases/database connections in the same pytest run.
An unfortunate side effect of this currently is that pytest now no longer groups the tests with different event loop implementations.
I haven't dug into pytest too much yet to figure out if that can be solved, but this is mostly just a cosmetic/convenience difference.
=> parameterize mysql_address in tests, allow passing one or more addresses via pytest args

CHANGES.txt, aiomysql/connection.py
implement a shortcut for determining secure connections, now supporting unix sockets
ports https://github.com/PyMySQL/PyMySQL/pull/696
ports check for server tls support for secure connections from https://github.com/PyMySQL/PyMySQL/pull/353
Unix sockets are now internally considered secure.
`sha256_password` and `caching_sha2_password` should now work for unix sockets (pending tests from #686)
=> implement a shortcut for determining secure connections, now supporting unix sockets

CHANGES.txt, aiomysql/connection.py, tests/test_sscursor.py
Awaits coroutine that was missed in #52.
Also fixes related test case.
SSCursor no longer raises an `InternalError` when the previous cursor was not properly 
Fixes #635
=> ensure coroutine is awaited when discarding results in SSCursor

CHANGES.txt, aiomysql/connection.py, docs/connection.rst, tests/base.py, tests/test_connection.py
The deprecated `no_delay` argument is removed from `Connection`.
`no_delay` may no longer be passed when a pool or connection is created.
no
=> remove deprecated no_delay argument

.flake8
allow lines of up to 88 characters.
this also provides compatibility with upcoming black formatting.
no
=> add flake8 config, set max-line-length to 88

tests/sa/test_sa_default.py, tests/sa/test_sa_transaction.py
add missing decorators to async sqlalchemy test methods
previously these methods were skipped in tests due to lack of native pytest async support
no
=> add missing decorators to async sqlalchemy test methods

.github/workflows/ci.yml
include tests in coverage report
no
=> include tests in coverage report

tests/conftest.py
remove unused `session_id` test fixture
this was introduced in #275 for running the database in a container but is no longer needed.
no
=> remove unused test code

.github/workflows/ci.yml, tests/conftest.py, tests/test_sha_connection.py
automatically detect db type and version in tests
this removes the need to pass the db type and version from environment variables.
it also makes it possible to pass connections to different databases to the same pytest run.
due to the version detection now relying on the parameterized mysql_address fixture
it is no longer compatible with tests independent from the connection, especially
relevant in test_sa_distil.py.
to resolve this the version gate was moved directly into test_sha_connection.py.
no
no
=> automatically detect db type and version in tests

CHANGES.txt, requirements-dev.txt, setup.py
while we do not yet strictly require it this simplifies maintenance.
e.g. the xfailing test from #712 gets a different error type starting with PyMySQL 0.10.0.
it will also allow us to adopt the backwards incompatible changes from PyMySQL 0.10 and 1.0.
as our test suite only runs with the latest supported PyMySQL version we currently cannot
reliably test older versions either.
PyMySQL <1.0 is no longer supported.
Fixes #518
=> bump minimal PyMySQL version to 1.0.0

tests/test_cursor.py
add xfailing test case for #545
this is ported from https://github.com/PyMySQL/PyMySQL/pull/450, also adds a test case for Cursor.execute()
no
#545
=> add xfailing test case for #545

CHANGES.txt, aiomysql/cursors.py, tests/test_cursor.py
port the changes from https://github.com/PyMySQL/PyMySQL/pull/450
`%%` is now required for literal `%` in `Cursor.executemany()`.
This aligns behavior with `Cursor.execute()`.
closes #545
=> Align % formatting in Cursor.executemany() with Cursor.execute()

CHANGES.txt, aiomysql/pool.py, tests/test_pool.py
New `closed` property for `Pool` instances, exposing whether the pool is closed.
New property available.
Fixes #463
=> add Pool.closed property as present in aiopg, fixes #463

tests/test_cursor.py, tests/test_sscursor.py
Reproducible test cases for #428.
This ports the test cases from https://github.com/PyMySQL/PyMySQL/pull/1033
Once https://github.com/PyMySQL/PyMySQL/pull/1033 is accepted and released we can also directly reference the constants in the tests.
An example failed test run without `pytest.mark.skip` can be found here and effectively just runs into a timeout on SSCursor: https://github.com/Nothing4You/aiomysql/actions/runs/1801465357
tests only.
#428
=> Add query timeout tests for #428

CHANGES.txt, setup.cfg, setup.py
- implement `python_requires` to replace python version check during setup.py execution
- relax PyMySQL dependency to only pin minimum required version
- pin SQLAlchemy version to below 1.4, as 1.4 is currently not compatible
- add mariadb keyword
=> Move static setuptools config to setup.cfg

CHANGES.txt, setup.cfg
Allow installing `aiomysql[rsa]` to depend on the supported `PyMySQL[rsa]` version.
no
fixes #557
=> Add rsa extras_require depending on PyMySQL[rsa]

.github/workflows/lint.yml, Makefile, requirements-dev.txt
Removes pyroma from test suite, as this isn't compatible with the upcoming implementation of `setuptools-scm`.
https://github.com/regebro/pyroma/issues/69
no
split from #734
=> Remove pyroma from tests

requirements-dev.txt
Avoid automatically deciding which runtime dependency versions are tested against.
no
split from #734
=> Pin exact runtime dependency versions for tests

.readthedocs.yaml
Add `.readthedocs.yaml` to set build settings.
As docs builds currently emit warnings we can't treat them as errors just yet.
no
no
=> Add readthedocs yaml config

Makefile
fix `make checkrst` to use `twine check` rather than `setup.py check`, `setup.py` was removed in #746.
no
fixes #756
=> fix `make checkrst`

CONTRIBUTING.rst
Specify explicit language for literal blocks in CONTRIBUTING.rst to reduce warnings in doc builds.
no
no
=> Specify explicit language for literal blocks in CONTRIBUTING.rst to reduce warnings in doc builds

README.rst
Fix GitHub Actions badge in readme after the workflow was renamed in #734.
=> Fix GHA badge in readme after #734

.github/workflows/ci-cd.yml
Workflow was referencing `CHANGES.txt` for inclusion in GitHub release notes but it didn't check out the git repo for this.
=> Checkout git source to access changelog for GitHub release creation

CHANGES.txt, aiomysql/connection.py, tests/test_basic.py
The SSL connection handshake character set is fixed to utf8, this PR is to fix that issue #775
Users should be able to establish SSL connections with the client charset parameter
#775
=> Fix SSL connection handshake charset not respecting client configuration

.github/workflows/ci-cd.yml
We can only upload a limited number of coverage reports for any commit anyway, this avoids turning these into test failures.
See e.g. https://github.com/aio-libs/aiomysql/runs/6143709548?check_suite_focus=true:
> [2022-04-24T01:46:32.439Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 400 - Bad Request - [ErrorDetail(string='Too many uploads to this commit.', code='invalid')]
=> Skip codecov uploads in scheduled daily tests

tests/test_issues.py
Until we have a real fix for the sporadic test failures it's causing unrelated changes to randomly fail tests.
By xfailing with this condition random test failures from this are removed, #714 will stay open to properly resolve this in the future.
no
#714
=> XFail test_issue_36 for now to avoid failing for unrelated changes

.codecov.yml, .github/workflows/ci-cd.yml
While we do currently have 40 expected reports total it's probably not worth increasing the minimum to that, as this would have to be kept in mind whenever the number of matrix jobs changes.
=> Delay codecov notifications until reports from all matrix jobs have been received

.github/workflows/ci-cd.yml
MariaDB 10.2 is no longer supported, remove it from from tests.
It's being replaced by MariaDB 10.8 in tests.
=> Update mariadb tests to 10.8, remove end of life mariadb 10.2

tests/sa/test_sa_connection.py, tests/sa/test_sa_transaction.py, tests/test_async_with.py
Fixes the following deprecation warning:
`SADeprecationWarning: The FromClause.count() method is deprecated, and will be removed in a future release.   Please use the count function available from the func namespace.`
References:
https://docs.sqlalchemy.org/en/13/core/metadata.html#sqlalchemy.schema.Table.count
https://docs.sqlalchemy.org/en/13/core/functions.html#sqlalchemy.sql.functions.count
No, tests only.
=> Fix use of deprecated SQLAlchemy functionality in tests

CHANGES.txt, setup.cfg
Bump minimal SQLAlchemy version to 1.3.
According to https://www.sqlalchemy.org/download.html all older versions are EOL, 1.3 is still in maintenance state.
`aiomysql[sa]` now requires SQLAlchemy version 1.3.
=> Bump minimal SQLAlchemy version to 1.3

.github/workflows/ci-cd.yml
Increase pytest timeout to 9.5 minutes (SIGINT), 10 minutes max in CI workflow.
Some runners appear to be very slow.
This will hopefully avoid failures like https://github.com/aio-libs/aiomysql/actions/runs/2642476373/attempts/1 in the future-
no
=> ci: increase pytest timeout to 9.5 minutes

tests/test_sscursor.py
Catch another warning in tests, so we have one less uncaught warning.
Also adjusts another instance of the same warning in the test to be more specific about which warning to catch.
no
=> catch another warning in tests

CHANGES.txt, aiomysql/pool.py, examples/example_ssl.py, tests/test_async_with.py, tests/test_issues.py, tests/test_pool.py, tests/test_sha_connection.py, tests/test_ssl.py
Deprecated method `Pool.get` was removed
Yes, see above.
no
=> remove deprecated Pool.get

CHANGES.txt, aiomysql/connection.py, tests/test_connection.py, tests/test_issues.py
Partially port https://github.com/PyMySQL/PyMySQL/pull/304
aiomysql now reraises the original exception during connect() if it's not `IOError`, `OSError` or `asyncio.TimeoutError`.
This was previously always raised as `OperationalError`.
`asyncio.TimeoutError` is a deprecated alias of `OSError` as of python 3.11, for consistency we already include here, so the exception handling won't differ across python versions.
fixes #792
=> Partially port PyMySQL#304

tests/sa/test_sa_connection.py
Add SQLAlchemy .in_ operator test case for #577
no
Relates to #577
=> Add SQLAlchemy .in_ operator test case for #577

CHANGES.txt, aiomysql/connection.py
Fix log exception, when login mysql using sha256_password_auth, exception throw 
`TypeError: not all arguments converted during string formatting` at `connection.py:1012` 
```
logger.debug(
"Received public key:\n",
self.server_public_key.decode('ascii')
)
```
No.
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with …
=> Fix log exception

.github/dependabot.yml
When multiple PRs are open this can quickly add up to lots of time consuming CI runs.
Dependabot previously rebased every time a new commit was added to master, as an updated CI run is required for PR merging.
=> Stop dependabot from autoamtically rebasing PRs to save CI time

.github/workflows/ci-cd.yml, requirements-dev.txt
Bring flake8 version in GitHub actions in sync with requirements-dev.txt.
Previously, GitHub actions would use an earlier version than dev requirements for local testing.
=> Bring flake8 version in GitHub actions in sync with requirements-dev.txt

.github/workflows/ci-cd.yml
Implement OIDC-based publishing to Test PyPI: https://docs.pypi.org/trusted-publishers/
This avoids having to use long lived secrets by replacing them with GitHub-issued OIDC tokens generated on demand.
This is split from #924 to only implement this for Test PyPI.
=> Implement Trusted Publishing for Test PyPI

CHANGES.txt, aiomysql/connection.py, aiomysql/cursors.py, aiomysql/sa/transaction.py, docs/conf.py, tests/conftest.py, tests/test_basic.py, tests/test_issues.py, tests/test_sha_connection.py, tests/test_sscursor.py
Modernize code to Python 3.7+ syntax.
Backwards compatibility to versions below Python 3.7 may get lost if this didn't already happen previously.
-
=> Modernize code with `pyupgrade --py37-plus`

.pre-commit-config.yaml
Add [pre-commit](https://pre-commit.com/) config for [pyupgrade](https://github.com/asottile/pyupgrade).
This also allows using the [pre-commit.ci](https://pre-commit.ci/) PR integration.
No, optional helper for aiomysql developers.
=> Add pre-commit config for pyupgrade --py37-plus

.github/workflows/ci-cd.yml, CHANGES.txt
Remove tests for EoL MariaDB versions 10.3, 10.7 and 10.8, added tests for MariaDB 10.9, 10.10, 10.11.
EoL MariaDB versions are no longer tested and may no longer work.
\-
=> Test only and all supported MariaDB versions

.github/workflows/ci-cd.yml
Implement OIDC-based publishing to PyPI: https://docs.pypi.org/trusted-publishers/
This avoids having to use long lived secrets by replacing them with GitHub-issued OIDC tokens generated on demand.
Publishing for Test PyPI has been implemented in #929 already.
=> Implement Trusted Publishing for prod PyPI

.github/workflows/ci-cd.yml
Replaces all uses of the [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) `set-output` functionality in the GHA workflow.
no, this is only CI workflow
fixes #864
=> Migrate away from using deprecated `set-output` in GHA

.github/workflows/ci-cd.yml
Change pypa/gh-action-pypi-publish action input names to kebab-case.
As of [v1.7.0](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.7.0), [pypi-publish](https://github.com/marketplace/actions/pypi-publish) uses kebab-case for input namings.
While snake_case names are still supported, they're now generating warnings
and will eventually be removed.
No, only CI workflow.
=> Migrate GHA pypi publish action inputs to kebab-case
