- aiomysql/connection.py
- tests/fixtures/my.cnf
- tests/test_connection.py
* added config file support
* fixed unix socket connection
> Feature config file

- .gitignore
- README.rst
- examples/example.py
- examples/example_pool.py
Hi,
This PR it's to fix examples.
Regards.
> Fix examples

- CHANGES.txt
- aiomysql/connection.py
- tests/sa/test_sa_transaction.py
1) rename ``Connection.connect`` to ``Connection._connect``;
2) refactor exception handling in `` _connect`` method: try to close ``self._writer`` in case of exception.
> Make connect method private

- tests/test_connection.py
- tests/test_cursor.py
> Remove DeprecationWarnings from tests

- aiomysql/connection.py
Synced changes in PyMySQL for sequence checking. What do we do about the tests for this? I kinda can't get how to test it.
> Added sequence checks for packets.

- aiomysql/connection.py
Azure Load Balancer has an ‘idle timeout’ setting of 4 minutes by default, so when he reached this limit he just close socket. Unfortunately aiomysql doesn't have mechanism to handle this case properly, right now aiomysql crashes by socket timeout:
```
Traceback (most recent call last):
File "/opt/trustologic/venv/lib/python3.6/site-packages/aiomysql/connection.py", line 558, in _read_bytes
data = yield from self._reader.readexactly(num_bytes)
File "/usr/lib/python3.6/asyncio/streams.py", line 668, in readexactly
yield from self._wait_for_data('readexactly')
File "/usr/lib/python3.6/asyncio/streams.py", line 458, in _wait_for_data
yield from self._waiter
File "/usr/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
data = self._sock.recv(self.max_size)
TimeoutError: …
```
> Add TCP Keepalive to connection

- docs/pool.rst
Autocommit default to false as key word argument to create pool method.
> Added autocommit key word argument to create_pool

- aiomysql/sa/result.py
- requirements-dev.txt
fix for https://github.com/aio-libs/aiomysql/issues/228
> fix sqla support

- aiomysql/__init__.py
Please merge this.
Someone forget a comma.
> fix __all__ in aiomysql/__init__

- aiomysql/sa/engine.py
Fixes #263 
Sorry for the delay :)
> Throw an exception when incompatible curos class is passed to SA engine

- aiomysql/pool.py
Reasoning: DeprecationWarning during _create_pool and it's normal usage
> Using `async with` instead of `with (await pool._cond)`

- .travis.yml
- aiomysql/connection.py
- aiomysql/cursors.py
- examples/example_cursors.py
- tests/test_deserialize_cursor.py
#334 
1.Deserialize json type data 
2.Inherit multiple types of cursors at the same time
> Deserialize json type data and Inherit multiple types of cursors at the same time

- docs/pool.rst
> Fix a typo and wrong indention

- CHANGES.txt
This PR tries to summarize changes that happened after the 0.0.20 release.
See this message for additional context: https://github.com/aio-libs/aiomysql/issues/466#issuecomment-668589737
No.
#466
> Fill changelog for 0.0.21 release

- CHANGES.txt
- Makefile
- aiomysql/__init__.py
- requirements-dev.txt
- setup.py
> Bump version and tweak setup.py

- .github/ISSUE_TEMPLATE/bug_report.yml
Add a GitHub issue template for bug reports
> create bug report template, based on aiohttp bug report template

- .github/ISSUE_TEMPLATE/bug_report.yml
- add PyMySQL and SQLAlchemy version to bug report template
> add PyMySQL and SQLAlchemy version to bug report template

- .github/ISSUE_TEMPLATE/feature_request.yml
Adds a feature request issue template.
Cherry-picked from #598
Only in GitHub issue creation.
Closes #598
> Introduce feature request issue template

- setup.py
Add python 3.10 in package classifiers now that we have tests for it.
no
> now that we have python 3.10 tests we can also advertise it

- tests/test_sscursor.py
Add test case for #635
no
#635
> add xfailing test case for #635

- CHANGES.txt
add note about PyMySQL 1.0 support in changelog
no
#643
> add note about PyMySQL 1.0 support in changelog

- requirements-dev.txt
test against sqlalchemy up to version 1.3.24
tests only
> test against sqlalchemy up to version 1.3.24

- .github/workflows/ci-cd.yml
> Actually update pip in CI workflow instead of just pretending to

- docs/pool.rst
> docs: Use context manager for cursor in pool example

- tests/conftest.py
- tests/sa/test_sa_compiled_cache.py
- tests/sa/test_sa_default.py
- tests/sa/test_sa_engine.py
ensure more resources are closed in tests.
this gets rid of a good amount of ResourceWarnings.
no
\-
> ensure more resources are closed in tests

- tests/sa/test_sa_compiled_cache.py
- tests/sa/test_sa_default.py
- tests/sa/test_sa_engine.py
pass ssl context in SA tests
no
\-
> pass ssl context in SA tests

- .github/workflows/ci-cd.yml
> Improve codecov flags

- CHANGES.txt
Adding release date and version number for 0.2.0.
> Update changelog for 0.2.0 release
